name: Android eChat CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    - develop
    - test/*
  
  schedule: 
    - cron: "0 2 ** 1-12"

  workflow_dispatch:

  workflow_run:
    branches: 
      - master
      - test/*
  

jobs:
  build:

    runs-on: 
    - ubuntu-latest
    - ubuntu-18.04
    - windows-latest/*

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
